default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: exercism_v3
  password: exercism_v3
  socket: <%= Exercism.config.mysql_socket %>
  timeout: 5000

  host: <%= Exercism.config.rds_master_endpoint %>
  port: <%= Exercism.config.rds_port %>

  variables:
    sql_mode: traditional

development:
  primary:
    <<: *default
    database: exercism_v3_development
  dj:
    <<: *default
    database: exercism_v3_dj_development
    migrations_paths: "db/dj_migrate"

test:
  primary:
    <<: *default
    database: exercism_v3_test
  dj:
    <<: *default
    database: exercism_v3_test
    migrations_paths: "db/dj_migrate"

production:
  primary:
    <<: *default
    database: exercism_v3
  dj:
    <<: *default
    database: exercism_v3_dj
    migrations_paths: "db/dj_migrate"
